export const keysMap = [
    [ // row 1
        {
            key: { ru: 'ё', en: '`' },
            shift: { ru: 'Ё', en: '~' },
            name: 'Backquote',
            class: 'key tilda Backquote',
        },
        {
            key: { ru: '1', en: '1' },
            shift: { ru: '!', en: '!' },
            name: 'Digit1',
            class: 'key Digit1',
        },
        {
            key: { ru: '2', en: '2' },
            shift: { ru: '"', en: '@' },
            name: 'Digit2',
            class: 'key Digit2',
        },
        {
            key: { ru: '3', en: '3' },
            shift: { ru: '№', en: '#' },
            name: 'Digit3',
            class: 'key Digit3',
        },
        {
            key: { ru: '4', en: '4' },
            shift: { ru: ';', en: '$' },
            name: 'Digit4',
            class: 'key Digit4',
        },
        {
            key: { ru: '5', en: '5' },
            shift: { ru: '%', en: '%' },
            name: 'Digit5',
            class: 'key Digit5',
        },
        {
            key: { ru: '6', en: '6' },
            shift: { ru: ':', en: '^' },
            name: 'Digit6',
            class: 'key Digit6',
        },
        {
            key: { ru: '7', en: '7' },
            shift: { ru: '?', en: '&' },
            name: 'Digit7',
            class: 'key Digit7',
        },
        {
            key: { ru: '8', en: '8' },
            shift: { ru: '*', en: '*' },
            name: 'Digit8',
            class: 'key Digit8',
        },
        {
            key: { ru: '9', en: '9' },
            shift: { ru: '(', en: '(' },
            name: 'Digit9',
            class: 'key Digit9',
        },
        {
            key: { ru: '0', en: '0' },
            shift: { ru: ')', en: ')' },
            name: 'Digit0',
            class: 'key Digit0',
        },
        {
            key: { ru: '-', en: '-' },
            shift: { ru: '_', en: '_' },
            name: 'Minus',
            class: 'key Minus',
        },
        {
            key: { ru: '=', en: '=' },
            shift: { ru: '+', en: '+' },
            name: 'Equal',
            class: 'key Equal',
        },
        {
            key: { ru: 'Backspace', en: 'Backspace' },
            name: 'Backspace',
            class: 'key key_backspace Backspace',
            noType: true,
        },
    ],
    [ // row 2
        {
            key: { ru: 'Tab', en: 'Tab' },
            name: 'Tab',
            class: 'key key_tab Tab',
            noType: true,
        },
        {
            key: { ru: 'й', en: 'q' },
            shift: { ru: 'Й', en: 'Q' },
            name: 'KeyQ',
            class: 'key KeyQ',
        },
        {
            key: { ru: 'ц', en: 'w' },
            shift: { ru: 'Ц', en: 'W' },
            name: 'KeyW',
            class: 'key KeyW',
        },
        {
            key: { ru: 'у', en: 'e' },
            shift: { ru: 'У', en: 'E' },
            name: 'KeyE',
            class: 'key KeyE',
        },
        {
            key: { ru: 'к', en: 'r' },
            shift: { ru: 'К', en: 'R' },
            name: 'KeyR',
            class: 'key KeyR',
        },
        {
            key: { ru: 'е', en: 't' },
            shift: { ru: 'Е', en: 'T' },
            name: 'KeyT',
            class: 'key KeyT',
        },
        {
            key: { ru: 'н', en: 'y' },
            shift: { ru: 'Н', en: 'Y' },
            name: 'KeyY',
            class: 'key KeyY',
        },
        {
            key: { ru: 'г', en: 'u' },
            shift: { ru: 'Г', en: 'U' },
            name: 'KeyU',
            class: 'key KeyU',
        },
        {
            key: { ru: 'ш', en: 'i' },
            shift: { ru: 'Ш', en: 'I' },
            name: 'KeyI',
            class: 'key KeyI',
        },
        {
            key: { ru: 'щ', en: 'o' },
            shift: { ru: 'Щ', en: 'O' },
            name: 'KeyO',
            class: 'key KeyO',
        },
        {
            key: { ru: 'з', en: 'p' },
            shift: { ru: 'З', en: 'P' },
            name: 'KeyP',
            class: 'key KeyP',
        },
        {
            key: { ru: 'х', en: '[' },
            shift: { ru: 'Х', en: '{' },
            name: 'BracketLeft',
            class: 'key BracketLeft',
        },
        {
            key: { ru: 'ъ', en: ']' },
            shift: { ru: 'Ъ', en: '}' },
            name: 'BracketRight',
            class: 'key BracketRight',
        },
        {
            key: { ru: '\\', en: '\\' },
            shift: { ru: '|', en: '|' },
            name: 'Backslash',
            class: 'key key_backslash Backslash',
        },
        {
            key: { ru: 'Del', en: 'Del' },
            name: 'Delete',
            class: 'key key_del Delete',
        },
    ],
    [ // row 3
        {
            key: { ru: 'CapsLk', en: 'CapsLk' },
            name: 'CapsLock',
            class: 'key CapsLock',
            noType: true,
        },
        {
            key: { ru: 'ф', en: 'a' },
            shift: { ru: 'Ф', en: 'A' },
            name: 'KeyA',
            class: 'key KeyA',
        },
        {
            key: { ru: 'ы', en: 's' },
            shift: { ru: 'Ы', en: 'S' },
            name: 'KeyS',
            class: 'key KeyS',
        },
        {
            key: { ru: 'в', en: 'd' },
            shift: { ru: 'В', en: 'D' },
            name: 'KeyD',
            class: 'key KeyD',
        },
        {
            key: { ru: 'а', en: 'f' },
            shift: { ru: 'А', en: 'F' },
            name: 'KeyF',
            class: 'key KeyF',
        },
        {
            key: { ru: 'п', en: 'g' },
            shift: { ru: 'П', en: 'G' },
            name: 'KeyG',
            class: 'key KeyG',
        },
        {
            key: { ru: 'р', en: 'h' },
            shift: { ru: 'Р', en: 'H' },
            name: 'KeyH',
            class: 'key KeyH',
        },
        {
            key: { ru: 'о', en: 'j' },
            shift: { ru: 'О', en: 'J' },
            name: 'KeyJ',
            class: 'key KeyJ',
        },
        {
            key: { ru: 'л', en: 'k' },
            shift: { ru: 'Л', en: 'K' },
            name: 'KeyK',
            class: 'key KeyK',
        },
        {
            key: { ru: 'д', en: 'l' },
            shift: { ru: 'Д', en: 'L' },
            name: 'KeyL',
            class: 'key KeyL',
        },
        {
            key: { ru: 'ж', en: ';' },
            shift: { ru: 'Ж', en: ':' },
            name: 'Semicolon',
            class: 'key Semicolon',
        },
        {
            key: { ru: 'э', en: '\'' },
            shift: { ru: 'Э', en: '"' },
            name: 'Quote',
            class: 'key Quote',
        },
        {
            key: { ru: 'Enter', en: 'Enter' },
            name: 'Enter',
            class: 'key key_enter Enter',
            noType: true,
        },
    ],
    [ // row 4
        {
            key: { ru: 'Shift', en: 'Shift' },
            name: 'ShiftLeft',
            class: 'key key_leftshift ShiftLeft',
            noType: true,
        },
        {
            key: { ru: 'я', en: 'z' },
            shift: { ru: 'Я', en: 'Z' },
            name: 'KeyZ',
            class: 'key KeyZ',
        },
        {
            key: { ru: 'ч', en: 'x' },
            shift: { ru: 'Ч', en: 'X' },
            name: 'KeyX',
            class: 'key KeyX',
        },
        {
            key: { ru: 'с', en: 'c' },
            shift: { ru: 'С', en: 'C' },
            name: 'KeyC',
            class: 'key KeyC',
        },
        {
            key: { ru: 'м', en: 'v' },
            shift: { ru: 'М', en: 'V' },
            name: 'KeyV',
            class: 'key KeyV',
        },
        {
            key: { ru: 'и', en: 'b' },
            shift: { ru: 'И', en: 'B' },
            name: 'KeyB',
            class: 'key KeyB',
        },
        {
            key: { ru: 'т', en: 'n' },
            shift: { ru: 'Т', en: 'N' },
            name: 'KeyN',
            class: 'key KeyN',
        },
        {
            key: { ru: 'ь', en: 'm' },
            shift: { ru: 'Ь', en: 'M' },
            name: 'KeyM',
            class: 'key KeyM',
        },
        {
            key: { ru: 'б', en: ',' },
            shift: { ru: 'Б', en: '<' },
            name: 'Comma',
            class: 'key Comma',
        },
        {
            key: { ru: 'ю', en: '.' },
            shift: { ru: 'Ю', en: '>' },
            name: 'Period',
            class: 'key Period',
        },
        {
            key: { ru: '.', en: '/' },
            shift: { ru: ',', en: '?' },
            name: 'Slash',
            class: 'key Slash',
        },
        {
            key: { ru: '▲', en: '▲' },
            name: 'ArrowUp',
            noType: true,
            class: 'key ArrowUp',
        },
        {
            key: { ru: 'Shift', en: 'Shift' },
            name: 'ShiftRight',
            class: 'key key_rightshift ShiftRight',
            noType: true,
        },
    ],
    [ // row 5
        {
            key: { ru: 'Ctrl', en: 'Ctrl' },
            name: 'ControlLeft',
            class: 'key key_leftctrl ControlLeft',
            noType: true,
        },
        {
            key: { ru: 'Alt', en: 'Alt' },
            name: 'AltLeft',
            class: 'key key_leftalt AltLeft',
            noType: true,
        },
        { 
            key: { ru: ' ', en: ' ' }, 
            name: 'Space',
            class: 'key key_space Space' 
        },
        {
            key: { ru: 'Alt', en: 'Alt' },
            name: 'AltRight',
            class: 'key key_rightalt AltRight',
            noType: true,
        },
        {
            key: { ru: 'Cntrl', en: 'Cntrl' },
            name: 'ControlRight',
            class: 'key key_rightctrl ControlRight',
            noType: true,
        },
        {
            key: { ru: '◄', en: '◄' },
            name: 'ArrowLeft',
            noType: true,
            class: 'key ArrowLeft',
        },
        {
            key: { ru: '▼', en: '▼' },
            name: 'ArrowDown',
            noType: true,
            class: 'key ArrowDown',
        },
        {
            key: { ru: '►', en: '►' },
            name: 'ArrowRight',
            noType: true,
            class: 'key ArrowRight',
        },
        {
            key: { ru: '🇷🇺', en: 'en' },
            name: 'Lang',
            class: 'key key_lang Lang',
            noType: true,
        },
    ],
];

// export default keysMap;